services:
  csd-database:
    image: postgres:14.11-alpine3.19
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ccdc_postgres_data:/var/lib/postgresql/data
      - ${POSTGRES_DUMP_LOC}:/tmp/csd-database.bak
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  ccdc_postgres_data:
    driver: local
